name: methodab
favicon: null
layout_spectrum: 0.5955252337735146
typography_spectrum: 0.2901988052763045
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3192909627687186
  lightness: 0.8814463545568287
  saturation: 0.4367725420743227
  rhythmicContrast: 0.16194034554064274
purpose: []
