name: methodab
favicon: null
layout_spectrum: 0.17958
typography_spectrum: 0.2901988052763045
title: The Art of Alcoholic Science
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f1f1'
    - '#000000'
    - '#676666'
    - '#333232'
    - '#afadad'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
